/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-03-25 15:36:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/style.css", Long.valueOf(1616686539454L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"navbar\">\r\n");
      out.write("\t\t<a href=\"index.jsp\">Home</a>\r\n");
      out.write("\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t<button class=\"dropbtn\">\r\n");
      out.write("\t\t\t\tOptions <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t<a href=\"list\">List All Vehicles</a> \r\n");
      out.write("\t\t\t\t<a href=\"VehicleForm.jsp\">Add new Vehicle</a> \r\n");
      out.write("\t\t\t\t<a href=\"removeForm\">Remove Vehicle</a>\r\n");
      out.write("\t\t\t\t<a href=\"edit\">Modify Vehicle</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<h1 class=\"header\">Welcome to Kensev's Car Management System!</h1>\r\n");
      out.write("</body>\r\n");
      out.write("<style>");
      out.write("@charset \"UTF-8\";\r\n");
      out.write("\r\n");
      out.write(".button {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tpadding: 0.3em 1.2em;\r\n");
      out.write("\tmargin: 0 0.3em 0.3em 0;\r\n");
      out.write("\tborder-radius: 2em;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-family: 'Roboto', sans-serif;\r\n");
      out.write("\tfont-weight: 300;\r\n");
      out.write("\tcolor: #FFFFFF;\r\n");
      out.write("\tbackground-color: #4eb5f1;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\ttransition: all 0.2s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("\tcolor: #848694;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar {\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tbackground-color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar a {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 14px 16px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown .dropbtn {\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding: 14px 16px;\r\n");
      out.write("\tbackground-color: inherit;\r\n");
      out.write("\tfont-family: inherit;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar a:hover, .dropdown:hover .dropbtn {\r\n");
      out.write("\tbackground-color: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tbackground-color: #f9f9f9;\r\n");
      out.write("\tmin-width: 160px;\r\n");
      out.write("\tbox-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content a {\r\n");
      out.write("\tfloat: none;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tpadding: 12px 16px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-content a:hover {\r\n");
      out.write("\tbackground-color: #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown:hover .dropdown-content {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\ttransform: translate(-50%, -50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box select {\r\n");
      out.write("\tbackground-color: #0563af;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding: 12px;\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tbox-shadow: 0 5px 25px rgba(0, 0, 0, 0.2);\r\n");
      out.write("\t-webkit-appearance: button;\r\n");
      out.write("\tappearance: button;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box::before {\r\n");
      out.write("\tcontent: \"\\f13a\";\r\n");
      out.write("\tfont-family: FontAwesome;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tright: 0;\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 28px;\r\n");
      out.write("\tline-height: 45px;\r\n");
      out.write("\tcolor: rgba(255, 255, 255, 0.5);\r\n");
      out.write("\tbackground-color: rgba(255, 255, 255, 0.1);\r\n");
      out.write("\tpointer-events: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box:hover::before {\r\n");
      out.write("\tcolor: rgba(255, 255, 255, 0.6);\r\n");
      out.write("\tbackground-color: rgba(255, 255, 255, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box select option {\r\n");
      out.write("\tpadding: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper {\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tpadding: 40px;\r\n");
      out.write("\tmax-width: 800px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table {\r\n");
      out.write("\tmargin: 0 0 40px 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tbox-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);\r\n");
      out.write("\tdisplay: table;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row {\r\n");
      out.write("\tdisplay: table-row;\r\n");
      out.write("\tbackground: #f6f6f6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".cell {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cell {\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".cell {\r\n");
      out.write("\tpadding: 6px 12px;\r\n");
      out.write("\tdisplay: table-cell;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modify {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#modifyTitle {\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("    font-size: larger;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("    font-style: italic;\r\n");
      out.write("    background-color: blue;\r\n");
      out.write("}");
      out.write("</style>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
