/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-03-26 11:05:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/css/loginStyle.css", Long.valueOf(1616756606323L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Login</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"FormBox\">\r\n");
      out.write("        <div class=\"inside\">\r\n");
      out.write("\r\n");
      out.write("            <h1>Kenan's Car Rental System</h1>\r\n");
      out.write("            <h2 style=\"color: grey;\">Login</h2>\r\n");
      out.write("            \r\n");
      out.write("           <form method=\"get\" action=\"LoginServlet\">\r\n");
      out.write("                <input class=\"text\" id=\"email\" type=\"text\" name=\"email\" id=\"email\" placeholder=\"Email\" required> \r\n");
      out.write("                <input class=\"text\" id=\"password\" type=\"password\" name=\"password\" id=\"password\" placeholder=\"Password\" required>\r\n");
      out.write("            <div class=\"redirect\">\r\n");
      out.write("                <button type=\"submit\" id=\"submit\"> Submit </button>\r\n");
      out.write("                <a id=\"link\" href=\"register.jsp\">Create account</a>\r\n");
      out.write("            </div>\r\n");
      out.write("             </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("<style>");
      out.write("body {\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("   background: rgb(134,41,41);\r\n");
      out.write("background: linear-gradient(90deg, rgba(134,41,41,1) 0%, rgba(185,82,42,1) 28%, rgba(210,194,187,1) 71%, rgba(92,92,92,1) 100%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("    font-family: Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.FormBox{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    margin-right: -50%;\r\n");
      out.write("    transform: translate(-50%, -50%);\r\n");
      out.write("    background: linear-gradient(90deg, rgba(251,251,251,1) 0%, rgba(92,92,92,1) 100%);\r\n");
      out.write("    max-width: 32rem;\r\n");
      out.write("    width: 90%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("div.inside {\r\n");
      out.write("    padding: 2.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write("h2 {\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    color: #848694;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    padding-top: 2.5rem;\r\n");
      out.write("    padding-bottom: 4rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input.text {\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-bottom: 2px solid #848694;\r\n");
      out.write("\r\n");
      out.write("    padding-top: 1rem;\r\n");
      out.write("    padding-bottom: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input.text:hover {\r\n");
      out.write("    border-bottom: 2px solid #0424c1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.redirect {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: flex-end;\r\n");
      out.write("    padding-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#submit {\r\n");
      out.write("    border-radius: 20px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    background-color: #59b6ee;\r\n");
      out.write("    color: white;\r\n");
      out.write("    max-width: 10rem;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 2.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#link {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    max-width: 10rem;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 2.5rem;\r\n");
      out.write("    padding-top: 2rem;\r\n");
      out.write("}");
      out.write("</style>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
